### ISSUE TITLE
502 Bad Gateway in Example data on page https://apify.com/jaroslavhejlek/instagram-scraper/example-data

### ISSUE THREAD

**Issue by gustawdaniel** [gippy/instagram-scraper#103]
![Screenshot from 2020-11-20 09-52-53](https://user-images.githubusercontent.com/16663028/99779974-23831480-2b16-11eb-9b56-17caf2c06a1b.png)

**Comment by metalwarrior665** [comment]
Hello, This is a temporary network problem on Apify's side. Example data tab will be removed soon anyway.
