### ISSUE TITLE
ERROR Error: Failed to log in using cookies, they are probably no longer usable and you need to set new ones.

### ISSUE THREAD

**Issue by genz10** [gippy/instagram-scraper#108]
Got the following error when trying to run the actor:
```
ERROR Error: Failed to log in using cookies, they are probably no longer usable and you need to set new ones.
```

Any idea what should I do? I got the cookie from mode "Retrieving cookie"

**Comment by pocesar** [comment]
are you mixing login with cookies?

**Comment by genz10** [comment]
No, even when I'm trying to use "retrieving cookie" mode, Instagram isn't sending me any verification code and eventually getting a timeout.

**Comment by pocesar** [comment]
can you try the latest version? are you running it on the platform or locally?

**Comment by genz10** [comment]
Running on the platform, when using latest version, I'm getting timeout:

`TimeoutError: waiting for selector `form button` failed: timeout 30000ms exceeded`

When running using temporary-beta version, I'm asked to input a verification code but I'm not receiving any.

**Comment by pocesar** [comment]
should be fixed in `beta` version
