### ISSUE TITLE
Comments were not captured

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#11]
https://my.apify.com/view/runs/woTmHzmDF9gwYsJTq

**Comment by eliehamouche** [comment]
Confirmed for me too - comments returns blank

**Comment by metalwarrior665** [comment]
Another case at
https://my.apify.com/view/runs/qrYn6vJjdbuSNmcLP

**Comment by metalwarrior665** [comment]
https://my.apify.com/view/runs/Nn4FwpRLwMFDJp6H5

**Comment by rchew** [comment]
Also tried this today on the Avengers Instagram post from the docs and no comments were returned from the run.  Below is the input JSON:

```
{
  "searchType": "user",
  "directUrls": [
    "https://www.instagram.com/p/Bw7jACTn3tC/"
  ],
  "resultsType": "comments",
  "proxy": {
    "useApifyProxy": true
  }
}
```

Any insights on this issue?

**Comment by metalwarrior665** [comment]
Hello,

The fix is on the way, we are processing multiple issues right now. I hope we can land PR in the next 2 weeks.

**Comment by metalwarrior665** [comment]
Comments finally work! There is still an issue that sometimes only 24 results are returned so we need to fix this asap.

**Comment by metalwarrior665** [comment]
Comments work nicely now.
