### ISSUE TITLE
extendOutputFunction doesn't seem to work

### ISSUE THREAD

**Issue by peteboere** [gippy/instagram-scraper#114]
To support some legacy code I have been trying to return the page HTML using `extendOutputFunction`:

````
{"extendOutputFunction": "($) => { return {html: document.documentElement.outerHTML} }"}
````

Simpler examples don't seem to be modifying the output data either:

````
{"extendOutputFunction": "($) => { return {foo: true} }"}
````

**Comment by pocesar** [comment]
extendOutputFunction is a no-op at the moment, the upcoming change to it will make it work again for all result types

**Comment by pocesar** [comment]
this is released as `beta` on the platform and documented on the README at bottom
