### ISSUE TITLE
get 'product_type' for posts to segregate video posts

### ISSUE THREAD

**Issue by vanishinggradient** [gippy/instagram-scraper#118]
Hi, I am attempting to scrape posts (within some period say 30 days) for a each profile, but I need information about posts type specifically 'product_type' so that I can segregate videos further into reels (clips'), igtv ('igtv') and video ('feed')

I can't seem  to figure out how to configure the output function to get the data

```
async (item) => {
    return {
        "product_type": item.product_type
    }
}
```

Thanks

**Comment by pocesar** [comment]
@vanishinggradient extend output function is a no-op at the moment, it require bigger changes to the scraper to be able to cover all the possible outputs

**Comment by vanishinggradient** [comment]
so if I wanted extra fields, is it the right approach to link to a fork of the github repo for ex. https://github.com/vanishinggradient/instagram-scraper as a different actor

**Comment by pocesar** [comment]
yes, if you're running it by yourself

**Comment by vanishinggradient** [comment]
I was able to product_type by runningt the fork but can't seem to get video_duration for some reason even though it is already in the list of fields

**Comment by vanishinggradient** [comment]
also, how I do run the docker container on local if I wanted to change stuff and debug (vscode remote containers), like it seems to ask for environment (suspecting it is input.json) i.e. proxy

**Comment by vanishinggradient** [comment]
still can't seem to get video_duration even after forking and linking to a different repo

**Comment by metalwarrior665** [comment]
Can you do a PR? We can easily merge it if it is non-breaking

**Comment by vanishinggradient** [comment]
done

but still can't get video_duration data for some reason

**Comment by metalwarrior665** [comment]
I merged it but currently it is in beta build, testing it.

**Comment by metalwarrior665** [comment]
I see there is `productType` but not video duration, perhaps it is not available in the response or at different field.

**Comment by metalwarrior665** [comment]
We added productType so I will close this issue but feel free to open another one about the video
