### ISSUE TITLE
Solve browser launch crash "Unable to open X display."

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#122]
This one is elusive. Chromium/Chrome doesn't matter. Happens as well on new version with the xvfb browser. It happens more on complex goto function and a lot of browser swaps.

From the latest discussions it seems like a problem with a disk IO and overwhelmed disk when retire-ring and launching a lot of browsers. If we cannot solve this on a platform level, we will need to perhaps reduce concurrency and spawn browsers differently (have more time in between so disk can catch up?).

**Comment by pocesar** [comment]
doing much better now
