### ISSUE TITLE
 anonymous access 

### ISSUE THREAD

**Issue by 89z** [gippy/instagram-scraper#137]
Is it possible to get post information, from a public page such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

without login?

**Comment by pocesar** [comment]
yes, you can

**Comment by 89z** [comment]
can you please provide more information? I didnt see any code here to do that

**Comment by pocesar** [comment]
follow the steps on how to run the scraper, as it isn't a node module or library https://sdk.apify.com/docs/guides/getting-started

**Comment by 89z** [comment]
that page doesnt provide any information for instagram...
