### ISSUE TITLE
Places can no longer be scraped (requires login)

### ISSUE THREAD

**Issue by loisshedd** [gippy/instagram-scraper#14]
Instagram have added a login requirement to location explorer so places can no longer be scraped.

**Comment by gippy** [comment]
You are correct. I have noticed it last week. There is a develop branch in this repository which adds multiple options and features, one of them is to provide login credentials (you can use any account, even newly created). Which if you use, then you should be able to scrape places again.

I'm going to merge the develop into master sometimes this week once I'm sure that the new version does not introduce any problems.

If you are using this on Apify platform, then you can use the new version immediately by seting `beta` as version in Task options.

**Comment by loisshedd** [comment]
Awesome, thanks :)

Can't seem to use the login functionality on Apify yet, though – when I switched to the beta version the features showed up on the Input tab but I can't actually input any details? (Maybe the problem is just me!)

**Comment by metalwarrior665** [comment]
The login option should be available in the latest version in the upcoming weeks.

**Comment by metalwarrior665** [comment]
The login option is on. Scraping location/places work even without login but only with the login you can scroll for more places.
