### ISSUE TITLE
Doesn't stop after configured limit

### ISSUE THREAD

**Issue by haf** [gippy/instagram-scraper#147]
I'm doing dev using the output of this actor, and would like to run very small batches, to test with.

However, when configuring 100 max results, it looks like this:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/193115/170089039-b76fa51b-9cfc-4162-9281-a7b449df473f.png">

How do I make this actor stop when I want it to?

**Comment by pocesar** [comment]
the results are per input. if you have 10 as input, and set 10 as max items, it will be 100 in total

**Comment by haf** [comment]
Thanks
