### ISSUE TITLE
Reads results for other tags than what I provided

### ISSUE THREAD

**Issue by haf** [gippy/instagram-scraper#148]
I'm trying to scrape a single hashtag, not related hashtags:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/193115/170089347-ccd6313b-cfc5-4993-a4b0-b4af97fc7cb8.png">

Just `#icaniwill`; however, the actor seems to be scraping more tags than I specify:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/193115/170089476-e8ea7c70-8488-4603-a910-854fe2bc9c6d.png">

**Comment by pocesar** [comment]
set search results limit to 1
