### ISSUE TITLE
Min-max params are the wrong way around

### ISSUE THREAD

**Issue by haf** [gippy/instagram-scraper#149]
<img width="435" alt="Screenshot 2022-05-24 at 19 01 44" src="https://user-images.githubusercontent.com/193115/170091876-17fbe7bc-4cba-4e5f-9b78-13826abe2f61.png">

**Comment by pocesar** [comment]
Instagram data is in descending order, that's the reason

**Comment by haf** [comment]
Oh, so you mean "from" is later than "until" in the INPUTs?
