### ISSUE TITLE
Names missing in data

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#2]
From: https://app.intercom.io/a/apps/kod1r788/inbox/inbox/1540415/conversations/22160831738

so I'm trying to get a list of instagram users for specific hash tags

but your tool doesn't get the profile name

for example we are trying to find instagram profiles for #cats

I need the profile name, and how many followers they have

**Comment by szabon** [comment]
Second this.  I am having the same issue.  ownerUsername column is null
 on every run.  Here is a run I did.  
[dataset_DrhEi5ARs8bCM8nZL.xlsx](https://github.com/gippy/instagram-scraper/files/3302535/dataset_DrhEi5ARs8bCM8nZL.xlsx)

**Comment by metalwarrior665** [comment]
This is actually possible in latest with the `expandOwners` input field
