### ISSUE TITLE
[Feature] Enhanced search and parsing by hashtags and results saving (requires login)

### ISSUE THREAD

**Issue by pidgeon777** [gippy/instagram-scraper#28]
Hello, do you think that by using your script, something like this could be achievable?:

- Obtain a list of users which created a post containing one or more particular hashtags.
- For each of the obtained users, also parse the following information:
    - bio
    - number of followers
    - number of followed accounts accounts
    - number of posts
    - account privacy (private or not)
    - profile picture availability
- Save all of the above information for each of the obtained users.

**Comment by metalwarrior665** [comment]
Hello,

The followers scraping requires a login. Also, some accounts may require you to follow them or be approved (these we basically cannot scrape). The login feature is currently in the `beta` version and you can try it. We should put it into the main build soon.

To achieve this workflow, you can first scrape maximum posts with a given hashtag. Then collect the usernames of these posts and scrape the profiles of the usernames.

**Comment by metalwarrior665** [comment]
The login feature is now on in the latest.

**Comment by pidgeon777** [comment]
Thanks for the great work!
