### ISSUE TITLE
Error thrown after 300~500 comments are loaded

### ISSUE THREAD

**Issue by AndreyBykov** [gippy/instagram-scraper#31]
When scraping comments it's working fine but after several hundred comments `Error: No node found for selector: [aria-label="Load more comments"]` is thrown.

Not the memory issue (tried with 4/16 GB - max used is a few hundred MB).

Locally it seems like sometimes it takes a bit more time for loading more comments (maybe some timeout which isn't logged properly?).
Also - after a few retries (~350 comments were loaded after each retry it could successfully finish with ~300). Actual number of comments is several thousand.

Example run id: `WizDYFakEut7Ed4ED` and `8MsvwhSYSQpuAkjdk`.

**Comment by metalwarrior665** [comment]
Haven't seen this error for a long time. The problem with comments is mainly that they start to load really slowly after reaching 500.
