### ISSUE TITLE
Explore possible performance problem

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#35]
One user is complaining that the runs of version 0.67 are consuming 3 times more resources than from 0.63

![run resources](https://user-images.githubusercontent.com/29718487/79964130-8c27e700-848a-11ea-88a2-1ad097cbf0f4.png)

**Comment by gippy** [comment]
This should hopefully be resolved now. There loading profile details was throwing errors and causing timeouts.

**Comment by gippy** [comment]
Resolved the issue, it was caused by 404 errors. In previous version 404 error ended immediately, while in the new one it did not and instead waited 60 seconds and then was retried 3 more times. Now it again ends immediately and is not retried.
