### ISSUE TITLE
Better handling of rate limited pages

### ISSUE THREAD

**Issue by AndrewSB** [gippy/instagram-scraper#44]
Hey! Quite often, I see that an IP in the proxy being used has been rate limited by instagram (it throws an error saying there was an unsupported page of the format

```
INFO  unsupported page {"LoginAndSignupPage":[{"captcha":{"enabled":false,"key":""},"gdpr_required":false,"tos_version":"row","username_hint":""}]}
ERROR BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.instagr$m.com/***/","retryCount":1,"id":"QLX7xkxpRTwq2SC"}
```

Can we handle these errors better by communicating that the IP address is being rate limited and we should stop assigning it in the pool?

**Comment by metalwarrior665** [comment]
Good point, this should definitely show a better error.

**Comment by AndrewSB** [comment]
bump - this would be really helpful to resolve in some way

**Comment by metalwarrior665** [comment]
Yeah, definitely. We are now working on a bigger merge so then this comes to play probably next month.

**Comment by AndrewSB** [comment]
Created #47 to do a minor workaround for this, really we should be telling the proxy that the IP being routed to needs to be removed from rotation for a little while

**Comment by metalwarrior665** [comment]
This is now working pretty well. The last part might be implementing SessionPool.

**Comment by pocesar** [comment]
the retries now work as expected using a new session
