### ISSUE TITLE
Instagram now requires login

### ISSUE THREAD

**Issue by TangrisJones** [gippy/instagram-scraper#49]
Hi, thanks for this great repo. It seems like instagram now requires a log in to view posts. Is there a workaround for this?

**Comment by TangrisJones** [comment]
this is actually a killer problem 😢

**Comment by metalwarrior665** [comment]
Thanks for your feedback. We will check this soon. Can you send us some URLs that don't work now?

**Comment by AndrewSB** [comment]
quick fix for this in #50 -- might have duplicated functionality in `develop`, lets get that merged soon

**Comment by pocesar** [comment]
@TangrisJones the login modal doesn't seem to affect the scrolling functionality. can you provide one profile that you're seeing this issue?

**Comment by TangrisJones** [comment]
Hi everyone, thank you for the prompt responses! I believe the issue is in the "post" pages themselves: [this post](https://www.instagram.com/p/CAYIkupheih/?igshid=19vazuooae0u6) requires authentication - which broke my code because it was expecting a post page but got a login page 😆. @AndrewSB seems to have a fix though! 😍

**Comment by TangrisJones** [comment]
I hope I am not missing anything, please let me know if I am wrong in any way.

**Comment by metalwarrior665** [comment]
The posts don't require authentication. It is just Instagram severely increasing anti-scraping protection. I'm testing what to do next.

**Comment by metalwarrior665** [comment]
Actually you are right. One post itself doesn't require it but scrolling through posts does it after about 36 of them.

**Comment by metalwarrior665** [comment]
@pocesar is right, the scrolling is still working fine under the login wall. I expect they will block this pretty soon but right now it still works. The more general problem is that they are blocking bad IPs generally.

**Comment by TangrisJones** [comment]
@metalwarrior665  You're right!! 😮 I was on VPN and I guess they were just requiring login because of that. GRRRRR instagram. Sorry for raising wrong issue. 

As an aside, how often are you getting through to scrape comments? I can't seems to get any in reliably.

**Comment by metalwarrior665** [comment]
@TangrisJones Our datacenter proxies started to fail a lot, some users reported 90% failed requests. Residential proxies seem to be doing ok but they are of course more expensive. We will see if there is a way around it. But since the datacenter proxies are blocked even if I use them in my own browser, I think they are just hard-banned at this point.

**Comment by metalwarrior665** [comment]
BTW: I have now merged the option to log in with cookies. That might help with some small loads. But you have to be very careful because they can block your account if you go crazy.

**Comment by TangrisJones** [comment]
@metalwarrior665 sounds good thank you for letting me know. Keep me updated if you find any other workarounds.

**Comment by metalwarrior665** [comment]
I just released a big update with many fixes and new features.

Login is only required if you want to scroll locations. Otherwise, everything works without login, you just need high quality (residential) proxies.
