### ISSUE TITLE
Research what assets can be safely blocked to lower the traffic

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#57]
This is needed because the scraper works stable only on residential proxies now. We could make this optional setting if there is some tradeoff.

**Comment by metalwarrior665** [comment]
We did some progress here and are blocking most assets but there is probably still space for improvement.

**Comment by pocesar** [comment]
works better with multiple direct urls, as all needed resources are cached in-memory now. one-off actor runs use 4MB+ per run
