### ISSUE TITLE
Failing to scrape on test, latest and beta

### ISSUE THREAD

**Issue by ladderapplication** [gippy/instagram-scraper#60]
Non-technical: Attempting to scrape posts from ~400 users... but am failing since the scraper went from scraping 50 posts at a time to 12 posts at a time. TEST also seems to no longer be running. Please help!

**Comment by metalwarrior665** [comment]
Hello,

I removed `TEST` build completely, use `latest` for stable run and `beta` to help us test new features. Could you possibly give me a link to the problematic runs? Most problems today are because of blocking from Instagram that is resolved by using residential proxy group.

**Comment by ladderapplication** [comment]
I have attempted this multiple times, with and without login cookies. How should I proceed?

https://my.apify.com/view/runs/znTzCSQcMwr929Trt <https://my.apify.com/view/runs/znTzCSQcMwr929Trt>

**Comment by metalwarrior665** [comment]
Yes, this is exactly the issue I was talking about. Scraping it requires residential proxies. Apify [offers their proxies](https://apify.com/proxy?pricing=residential-ip#pricing) but you can use any other provider too.

**Comment by afedotov89** [comment]
Hello! useApifyProxy=true does not use resident proxies?

**Comment by metalwarrior665** [comment]
`useApifyProxy` uses just datacenter proxies by itself. You have to also pick the proxy groups. 

`apifyProxyGroups: ['RESIDENTIAL']`

**Comment by metalwarrior665** [comment]
I just deployed a big new update. Should fix most problems.
