### ISSUE TITLE
Why aren't all the posts scraped?

### ISSUE THREAD

**Issue by csdrli** [gippy/instagram-scraper#67]
Search posts by hashtag:

The output says: 

72 posts loaded, 72/749 posts scraped

It says "Reached post with older date than our limit: Sun May 26 2019 02:05:04 GMT-0400 (Eastern Daylight Time). Finishing scrolling...", but scrapePostsUntilDate is set to "2000-01-01"

Login cookies are provided in the input.

Thanks.

--------------------------

The whole output is below:

INFO  System info {"apifyVersion":"0.20.4","apifyClientVersion":"0.6.0","osType":"Darwin","nodeVersion":"v12.18.0"}
WARN  Cookies were used, setting maxConcurrency to 1 and using one proxy session!
INFO  Searching for "preeclampsiasurvivor"
INFO  Found  search results. Limited to 100.
INFO  Search found 8 URLs after limiting to 100:
[
  'https://www.instagram.com/explore/tags/preeclampsiasurvivor/',
  'https://www.instagram.com/explore/tags/preeclampsiasurvivors/',
  'https://www.instagram.com/explore/tags/preeclampsiasurvivorx2/',
  'https://www.instagram.com/explore/tags/preeclampsiasurvivorsandproudofit/',
  'https://www.instagram.com/explore/tags/preeclampsiasurvivorx4/',
  'https://www.instagram.com/explore/tags/preeclampsiasurvivorp/',
  'https://www.instagram.com/explore/tags/preeclampsiasurvivortimes2/',
  'https://www.instagram.com/explore/tags/preeclampsiasurvivorsindonesia/'
]
INFO  PuppeteerCrawler:AutoscaledPool:Snapshotter: Setting max memory of this run to 4096 MB. Use the APIFY_MEMORY_MBYTES environment variable to override it.
INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
INFO  Launching Puppeteer {"apifyProxyUrls":["http://a:a@192.168.5.201:3128"],"stealth":true,"useChrome":true,"ignoreHTTPSErrors":true,"args":["--enable-features=NetworkService","--ignore-certificate-errors","--no-sandbox"],"timeout":15000,"headless":false,"executablePath":"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","defaultViewport":{"width":1366,"height":768}}
INFO  Launching Puppeteer {"apifyProxyUrls":["http://a:a@192.168.5.201:3128"],"stealth":true,"useChrome":true,"ignoreHTTPSErrors":true,"args":["--enable-features=NetworkService","--ignore-certificate-errors","--no-sandbox"],"timeout":15000,"headless":false,"executablePath":"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","defaultViewport":{"width":1366,"height":768}}
INFO  Tag "preeclampsiasurvivor": 66 posts loaded, 66/13735 posts scraped
INFO  Tag "preeclampsiasurvivors": 72 posts loaded, 72/749 posts scraped
INFO  Tag "preeclampsiasurvivorsandproudofit": 1 posts loaded, 1/1 posts scraped
INFO  Tag "preeclampsiasurvivorx2": 1 posts loaded, 1/1 posts scraped
INFO  Tag "preeclampsiasurvivorx4": 1 posts loaded, 1/1 posts scraped
INFO  Tag "preeclampsiasurvivorp": 1 posts loaded, 1/1 posts scraped
INFO  Tag "preeclampsiasurvivortimes2": 1 posts loaded, 1/1 posts scraped
INFO  Tag "preeclampsiasurvivorsindonesia": 1 posts loaded, 1/1 posts scraped
INFO  PuppeteerCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
INFO  PuppeteerCrawler: Final request statistics: {"avgDurationMillis":2337,"perMinute":51,"finished":8,"failed":0,"retryHistogram":[8]}

**Comment by metalwarrior665** [comment]
Thank you for the report.

1) There was an issue with the scrolling with hashtags and I have pushed a fix.
2) I wasn't able to reproduce the `scrapePostsUntilDate` problem, seems to be working fine.

**Comment by csdrli** [comment]
Works now. Thanks!
