### ISSUE TITLE
Issue getting total amount of posts

### ISSUE THREAD

**Issue by jaspzz** [gippy/instagram-scraper#72]
There seems to be an issue in both v.0.0 and v.0.1.

v.0.0
Keeps giving the error message "ERROR Failed to log in using cookies, they are probably no longer usable and you need to set new ones." (same cookies work in v.0.1.)

v.0.1
For several accounts, I keep receiving the log "User "XXX": 0 posts loaded, 12/null posts scraped". After a while, the execution succeeds even though not all posts have been extracted (around 2000 of 20.000 posts).

**Comment by metalwarrior665** [comment]
Thanks for the report. Extracting a huge amount of posts is tricky as Instagram can block you completely once you scroll too far, we are working on improvement in scrolling that could solve this.

Can you send me your input for the failing ones? Using non-logged version is preferred.

**Comment by pocesar** [comment]
the comment count is actually the total comments (including replies to comments). it doesn't load sub comments since it requires interaction with the page, right now only loads top most comments. tracked in #53
