### ISSUE TITLE
Hashtag search in Korean doesn't work

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#73]
It does search the different hashtags but fails to open the page with posts with ```Error: Place/location or hashtag page didn't load properly, trying again...```. Perhaps just a different selector.

Example input 

```{
  "search": "경의선숲길",
  "searchType": "hashtag",
  "searchLimit": 100,
  "resultsType": "posts",
  "resultsLimit": 10000,
  "maxRequestRetries": 5,
  "scrollWaitSecs": 15,
  "proxy": {
    "useApifyProxy": true,
    "apifyProxyGroups": [
      "RESIDENTIAL"
    ]
}
```

**Comment by pocesar** [comment]
the immediate issue is fixed, but it will fail randomly for adjacent tags

**Comment by pocesar** [comment]
works, but randomly fails to load the page on residential

**Comment by pocesar** [comment]
seems to be working as intended, although limited after a hundred posts
