### ISSUE TITLE
Scraping wrong instagram account

### ISSUE THREAD

**Issue by wfaguy** [gippy/instagram-scraper#77]
Hi, I've added a certain instagram account to the scraper.  I'm giving a "user-account" as url "https://www.instagram.com/name_of_account/" but it's returning images from a "location-account".  
I have noticed that the location name & username are the same.

**Comment by metalwarrior665** [comment]
Hello,

Thanks for submitting it. Could you please send me the full JSON input so I can test it out? Thanks.

**Comment by wfaguy** [comment]
{

  "searchType": "user",

  "directUrls": [

    "https://www.instagram.com/uma_selectiekantoor/",

    "https://www.instagram.com/squadt.be/",

    "https://www.instagram.com/couteaux_en_co/"

  ],

  "resultsType": "posts",

  "resultsLimit": 10,

  "proxy": {

    "useApifyProxy": true,

    "apifyProxyGroups": [

      "RESIDENTIAL"

    ]

  },

  "expandOwners": false

}

 

It’s the 3rd url : it’s grabbing images from another Instagram link, not that one.

 

Met vriendelijke groeten,

Mirko

+32 496 122 285

 

Van: Lukáš Křivka <notifications@github.com> 
Verzonden: zaterdag 15 augustus 2020 9:03
Aan: gippy/instagram-scraper <instagram-scraper@noreply.github.com>
CC: WFAGuy.com <mirko@wfaguy.com>; Author <author@noreply.github.com>
Onderwerp: Re: [gippy/instagram-scraper] Scraping wrong instagram account (#77)

 

Hello,

Thanks for submitting it. Could you please send me the full JSON input so I can test it out? Thanks.

**Comment by vcmirko** [comment]
No one any comment on this?

**Comment by metalwarrior665** [comment]
Sorry for the delay. I cannot reproduce this, seems to work fine.

```
{
  "searchType": "user",
  "directUrls": [
    "https://www.instagram.com/couteaux_en_co/"
  ],
  "resultsType": "posts",
  "resultsLimit": 10,
  "proxy": {
    "useApifyProxy": true,
    "apifyProxyGroups": [
      "RESIDENTIAL"
    ]
  },
  "followingLimit": 10,
  "followedByLimit": 10,
  "expandOwners": false,
  "extendOutputFunction": "($) => { return {} }",
  "searchLimit": 10,
  "maxRequestRetries": 5,
  "scrollWaitSecs": 15,
  "likedByLimit": 0
}
```

Gives back
https://api.apify.com/v2/datasets/jq695twZdH8N4FuzK/items?format=json&clean=1

which looks exactly like 
https://www.instagram.com/couteaux_en_co/

**Comment by vcmirko** [comment]
Weird, if i am querying with rest from apify i get other results.  

Verstuurd vanaf mijn iPhone
