### ISSUE TITLE
Consider adding a login option

### ISSUE THREAD

**Issue by metalwarrior665** [gippy/instagram-scraper#8]
We already got two use-cases that would use a logged-in user. Since the solution is built via PuppeteerCrawler, adding of login option will require just slight modification.

The argument that users may ban their account is valid but the description should be alerting enough.

**Comment by TangrisJones** [comment]
has this been rolled out?

**Comment by metalwarrior665** [comment]
It is in develop branch which we have to merge in. Hope to do it this or next week.

**Comment by metalwarrior665** [comment]
The login option via cookies is in latest.
