### ISSUE TITLE
Downloading private accounts' data - Question

### ISSUE THREAD

**Issue by sayedsaddam** [gippy/instagram-scraper#85]
Hi, I have a question. Does it have the ability to download private accounts' data. I've seen another package that doesn't allow you to download a private account when you're not following it?

So please, lemme know if there's some feature in it to download private accounts while you're not following them.
any help would be highly appreciated.

Thanks
Regards

**Comment by metalwarrior665** [comment]
Hello,

No, this is not possible. It would basically have to hack their database or find a leak of these data which we cannot and don't want to do. To get to private data, you need to add login cookies and have access to that private account.

**Comment by sayedsaddam** [comment]
OK, thank you for your precious time that you took responding me.
