### ISSUE TITLE
Getting follower counts?

### ISSUE THREAD

**Issue by andosmith** [gippy/instagram-scraper#9]
In the documentation you mention that you're unable to get follower counts using this tool.  Wouldn't it be possible with Apify's proxy setup?  Instagram seems to require login or re-login after a certain number of profile page fetches, but you'd think those limits could be circumvented with enough proxies (depending on the number of user follower counts needed, I guess.)

**Comment by metalwarrior665** [comment]
Followers are only available with login. This feature will soon be available in the latest build.

**Comment by metalwarrior665** [comment]
The login feature is on, you can scrape followers once logged in.
